# This pipeline is only meant to be executed manually
trigger: none

pool:
  name: Default

variables:
  - group: aks.variables
  - group: azure.variables

steps:

- script: chmod u+x ./aks/*.sh
  displayName: "Grant shell execution permissions"

- script: |
    ./00-az-login.sh
  displayName: 'Login to Azure with service principal'
  workingDirectory: ./aks
  env:
    AZ_SP_SECRET: $(AZ_SP_SECRET)

- script: |
    ./99-delete_rg.sh
  displayName: 'Delete resource group'
  workingDirectory: ./aks
