export RESOURCE_GROUP=${RESOURCE_GROUP:-"aks_rg"}   #The resource group in which the AKS cluster is to be created
export LOCATION=${LOCATION:-"westeurope"}           #The region in which the AKS cluster is to be created
export VM_SIZE=${VM_SIZE:-"Standard_B4ms"}          #The VM size to be used for worker nodes
export CLUSTER_NAME=${CLUSTER_NAME:-"myaks"}        #The name of the AKS cluster
export DNS_LABEL_NAME=${DNS_LABEL_NAME:-$CLUSTER_NAME"ingress"}     #The prefix for the DNS name allocated to the ingress, full path will be ${DNS_LABEL_NAME}.${LOCATION}.cloudapp.azure.com
export NODE_COUNT=${NODE_COUNT:-"1"}                #The number of node in the cluster
export LOAD_BALANCER_SKU=${LOAD_BALANCER_SKU:-"basic"}              #The load balancer SKU
export SAG_DOCKER_URL=${SAG_DOCKER_URL:-"sagcr.azurecr.io"}         #The URL of the SAG container registry
export FLUENT_ELASTICSEARCH_HOST=${FLUENT_ELASTICSEARCH_HOST:-"localhost"}  #The url of the elastic search to which FluentD can send log data
export FLUENT_ELASTICSEARCH_PORT=${FLUENT_ELASTICSEARCH_PORT:-"8080"}       #The port of the elastic searhc
export FLUENT_ELASTICSEARCH_SCHEME=${FLUENT_ELASTICSEARCH_SCHEME:-"http"}   #The scheme to be use to connect to Elastic search (http or https)
export DOMAIN_NAME=${DOMAIN_NAME:-"example.com"}    #Your domain name (used to configure ingresses)